In [1]:
from pathlib import Path 
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd
from collections import OrderedDict
import sys
import os
import seaborn as sns

In [2]:
data_root = Path("/Volumes/Samsung_T5/MIT/abcd/release_05/abcd-data-release-5.1/core")
ph_section = "physical-health"
mh_section= 'mental-health'
ph_path = Path(data_root, ph_section)
mh_path = Path(data_root, mh_section)
meds_filename = "ph_p_meds.csv"
mh_serv_filename_y = 'mh_p_ksads_bg.csv'
mh_serv_filename_p = 'mh_p_ksads_bg.csv'
#su_p_plus
#su_y_sui
#su_y_tlfb
#sd_y_rd

meds = pd.read_csv(Path(ph_path, meds_filename), dtype=object)
mh_serv_p = pd.read_csv(Path(mh_path, mh_serv_filename_y), dtype=object)
mh_serv_y = pd.read_csv(Path(mh_path, mh_serv_filename_p), dtype=object)

In [3]:
meds_name = meds['med1_rxnorm_p']
meds_index = meds.index[meds['med1_rxnorm_p'].notna()]
print(len(meds_name[meds_name.str.contains('Clonidine', na = False)]))
ADHD_meds = ['Methylphenidate', 'atomoxetine', 'guanfacine', 'clonidine'] # not exhaustive, verfiy presence with upper and lowercase!

66

In [4]:
meds

,src_subject_id,eventname,brought_medications,med1_rxnorm_p,medication1_dosage,med1_dk,rx_med1_units_p,rx_med1_xr,rx_med1_prn,rx_med1_sched_p,...,med6_rxnorm_1yr_p,med7_2wk_p,med7_rxnorm_1yr_p,med8_rxnorm_1yr_p,med8_2wk_p,cbd_usage_type___2,med9_2wk_p,med9_rxnorm_1yr_p,cbd_usage_type___3,cbd_usage_type___4
0,NDAR_INV003RTV85,baseline_year_1_arm_1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NDAR_INV003RTV85,1_year_follow_up_y_arm_1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NDAR_INV003RTV85,2_year_follow_up_y_arm_1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NDAR_INV003RTV85,3_year_follow_up_y_arm_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NDAR_INV005V6D2C,baseline_year_1_arm_1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48986,NDAR_INVZZZP87KR,baseline_year_1_arm_1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48987,NDAR_INVZZZP87KR,1_year_follow_up_y_arm_1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48988,NDAR_INVZZZP87KR,2_year_follow_up_y_arm_1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48989,NDAR_INVZZZP87KR,3_year_follow_up_y_arm_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48990,NDAR_INVZZZP87KR,4_year_follow_up_y_arm_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
mh_serv_p[mh_serv_p['kbi_p_c_scheck1'].notna()]['kbi_p_c_scheck1']

0        0
4        0
8        0
11       0
14       0
        ..
48744    0
48749    0
48754    0
48759    0
48761    0
Name: kbi_p_c_scheck1, Length: 11863, dtype: object

In [42]:
cols_mh_serv = [col for col in mh_serv_p.columns if col.startswith('kbi_p_c_scheck') or col.startswith('kbi_p_c_serviceschecklist')] 
mh_serv_p_qst = mh_serv_p[cols_mh_serv]
mh_serv_p_qst

,kbi_p_c_scheck1,kbi_p_c_scheck2,kbi_p_c_scheck3,kbi_p_c_scheck4,kbi_p_c_scheck5,kbi_p_c_scheck6,kbi_p_c_scheck7,kbi_p_c_scheck8,kbi_p_c_scheck9,kbi_p_c_scheck10,kbi_p_c_serviceschecklist3l8,kbi_p_c_serviceschecklist3l9,kbi_p_c_serviceschecklist3l777,kbi_p_c_serviceschecklist3l1,kbi_p_c_serviceschecklist3l2,kbi_p_c_serviceschecklist3l3,kbi_p_c_serviceschecklist3l4,kbi_p_c_serviceschecklist3l5,kbi_p_c_serviceschecklist3l6,kbi_p_c_serviceschecklist3l7
0,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48761,0,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

['kbi_p_c_scheck1',
 'kbi_p_c_scheck2',
 'kbi_p_c_scheck3',
 'kbi_p_c_scheck4',
 'kbi_p_c_scheck5',
 'kbi_p_c_scheck6',
 'kbi_p_c_scheck7',
 'kbi_p_c_scheck8',
 'kbi_p_c_scheck9',
 'kbi_p_c_scheck10',
 'kbi_p_c_serviceschecklist3l8',
 'kbi_p_c_serviceschecklist3l9',
 'kbi_p_c_serviceschecklist3l777',
 'kbi_p_c_serviceschecklist3l1',
 'kbi_p_c_serviceschecklist3l2',
 'kbi_p_c_serviceschecklist3l3',
 'kbi_p_c_serviceschecklist3l4',
 'kbi_p_c_serviceschecklist3l5',
 'kbi_p_c_serviceschecklist3l6',
 'kbi_p_c_serviceschecklist3l7']